//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robust
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentEntity
    {
        public int ID { get; set; }
        public int EntityTypeID { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
    }
}
