//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robust
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentFieldValue
    {
        public int ID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public int FieldID { get; set; }
        public int ValueNumber { get; set; }
    }
}
