//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robust
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldValue
    {
        public int ID { get; set; }
        public Nullable<int> EntityID { get; set; }
        public int FieldID { get; set; }
        public int ValueNumber { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual FieldValues_Bit BitValue { get; set; }
        public virtual FieldValues_Date DateValue { get; set; }
        public virtual FieldValues_Decimal DecimalValue { get; set; }
        public virtual Field Field { get; set; }
        public virtual FieldValues_ForeignKey ForeignKeyValue { get; set; }
        public virtual FieldValues_FreeText FreeTextValue { get; set; }
        public virtual FieldValues_Int IntValue { get; set; }
        public virtual FieldValues_Text TextValue { get; set; }
    }
}
