//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robust
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldValues_Int
    {
        public int FieldValueID { get; set; }
        public int Value { get; set; }
    
        public virtual FieldValue FieldValue { get; set; }
    }
}
