//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robust
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.FieldValues = new HashSet<FieldValue>();
        }
    
        public int ID { get; set; }
        public int EntityTypeID { get; set; }
        public int FieldTypeID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool Mandatory { get; set; }
        public int MinNumber { get; set; }
        public Nullable<int> MaxNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldValue> FieldValues { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual FieldType FieldType { get; set; }
    }
}
